from __future__ import annotations

from .constants import ENGINE_HOOKS, HOOK_SIGS


def _dbg(name: str, enabled: bool) -> str:
    if not enabled:
        return ""
    return (
        f'    if ( we_debug.integer == 1 )\n'
        f'        G_Print( "WE {name}\\n" );\n'
    )


def generate_wrappers(mode: str, *, debug: bool) -> str:
    """Generate GT_* entry points that dispatch through the WE hook registry."""
    lines = [
        "// AUTO-GENERATED by scripts/inject — do not edit",
        f"// mode={mode}",
        "// Dispatches via funcdef registries in core/hooks.as + core/cmds.as",
        "",
    ]

    for name in ENGINE_HOOKS:
        rettype, params, args = HOOK_SIGS[name]
        call = f"{name}__orig({args})" if args else f"{name}__orig()"
        dbg = _dbg(name, debug)
        param_sig = f" {params}" if params else ""
        dbg_lines = [dbg.rstrip()] if dbg else []

        if name == "GT_InitGametype":
            lines += [
                "void GT_InitGametype()",
                "{",
                *dbg_lines,
                "    WE_Init();",
                f"    {call};",
                "    WE_Init_After();",
                "}",
                "",
            ]
            continue

        if name == "GT_Command":
            lines += [
                "bool GT_Command( Client @client, const String &cmdString, "
                "const String &argsString, int argc )",
                "{",
                *dbg_lines,
                "    if ( we_enabled.integer != 1 )",
                f"        return {call};",
                "    if ( WE_Cmds_Dispatch( client, cmdString, argsString, argc ) )",
                "        return true;",
                f"    return {call};",
                "}",
                "",
            ]
            continue

        if name == "GT_ThinkRules":
            lines += [
                "void GT_ThinkRules()",
                "{",
                *dbg_lines,
                "    if ( we_enabled.integer == 1 && WE_Hooks_DispatchThinkBefore() )",
                "        return;",
                f"    {call};",
                "    if ( we_enabled.integer == 1 )",
                "        WE_Hooks_DispatchThinkAfter();",
                "}",
                "",
            ]
            continue

        if name == "GT_ScoreEvent":
            lines += [
                "void GT_ScoreEvent( Client @client, const String &score_event, "
                "const String &args )",
                "{",
                *dbg_lines,
                "    if ( we_enabled.integer == 1 && "
                "WE_Hooks_DispatchScoreEventBefore( client, score_event, args ) )",
                "        return;",
                f"    {call};",
                "    if ( we_enabled.integer == 1 )",
                "        WE_Hooks_DispatchScoreEventAfter( client, score_event, args );",
                "}",
                "",
            ]
            continue

        if name == "GT_Shutdown":
            lines += [
                "void GT_Shutdown()",
                "{",
                *dbg_lines,
                f"    {call};",
                "    if ( we_enabled.integer == 1 )",
                "        WE_Hooks_DispatchShutdown();",
                "}",
                "",
            ]
            continue

        if rettype == "void":
            lines += [
                f"void {name}({param_sig})",
                "{",
                *dbg_lines,
                f"    {call};",
                "}",
                "",
            ]
        elif rettype == "bool":
            lines += [
                f"bool {name}({param_sig})",
                "{",
                *dbg_lines,
                f"    return {call};",
                "}",
                "",
            ]
        elif rettype == "Entity @":
            lines += [
                f"Entity @{name}({param_sig})",
                "{",
                *dbg_lines,
                f"    return {call};",
                "}",
                "",
            ]
        elif rettype == "String @":
            lines += [
                f"String @{name}({param_sig})",
                "{",
                *dbg_lines,
                f"    return {call};",
                "}",
                "",
            ]

    return "\n".join(lines) + "\n"
